# Generated by Django 3.2.8 on 2021-10-19 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('pessoa', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('ativo', models.BooleanField(default=True, verbose_name='Usuário ativo')),
                ('equipe', models.BooleanField(default=False, verbose_name='Membro da equipe')),
                ('superusuario', models.BooleanField(default=True, verbose_name='Admin')),
                ('criadoem', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizadoem', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Perfil_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome/Razão Social')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('celular', models.IntegerField(null=True, verbose_name='Celular')),
                ('cep', models.CharField(max_length=8, verbose_name='Cep')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereco')),
                ('numero', models.CharField(max_length=8, verbose_name='Número')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=255, verbose_name='Estado')),
                ('situacao', models.CharField(choices=[('2', 'Reprovado'), ('1', 'Aprovado'), ('0', 'Pendente')], default='Pendente', max_length=13, verbose_name='Situação')),
                ('atualizadoem', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
