# Generated by Django 3.2.8 on 2021-10-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='situacao',
            field=models.CharField(choices=[('0', 'Pendente'), ('2', 'Reprovado'), ('1', 'Aprovado')], default='Pendente', max_length=13, verbose_name='Situação'),
        ),
    ]
