# Generated by Django 3.1 on 2021-10-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.IntegerField(null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='situacao',
            field=models.CharField(choices=[('0', 'Pendente'), ('2', 'Reprovado'), ('1', 'Aprovado')], default='Pendente', max_length=13, verbose_name='Situação'),
        ),
    ]
