# Generated by Django 3.2.8 on 2021-10-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='cpf_cnpj',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil_usuario',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil_usuario',
            name='situacao',
            field=models.CharField(choices=[('2', 'Reprovado'), ('0', 'Pendente'), ('1', 'Aprovado')], default='Pendente', max_length=13, verbose_name='Situação'),
        ),
    ]
