# Generated by Django 3.2.8 on 2021-10-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='superusuario',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
