# Generated by Django 3.2.8 on 2021-10-28 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20211023_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='celular',
            field=models.CharField(default=django.utils.timezone.now, max_length=18, verbose_name='Celular'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil_usuario',
            name='cpf_cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil_usuario',
            name='situacao',
            field=models.CharField(choices=[('0', 'Pendente'), ('2', 'Reprovado'), ('1', 'Aprovado')], default='Pendente', max_length=13, verbose_name='Situação'),
        ),
    ]
