# Generated by Django 3.2.8 on 2024-07-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20211028_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='situacao',
            field=models.CharField(choices=[('1', 'Aprovado'), ('2', 'Reprovado'), ('0', 'Pendente')], default='Pendente', max_length=13, verbose_name='Situação'),
        ),
    ]
