# Generated by Django 3.2.8 on 2024-07-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_perfil_usuario_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_usuario',
            name='situacao',
            field=models.CharField(choices=[('2', 'Reprovado'), ('0', 'Pendente'), ('1', 'Aprovado')], default='Pendente', max_length=13, verbose_name='Situação'),
        ),
    ]
